name: python-linter-check
on:
    push:
        branches: [ main ]
    pull_request:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: pull latest commit
              uses: actions/checkout@v3

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'

            - name: Install depenencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8
                pip install pylint
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name : Lint with flake8
              run: |
                flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 src --count --max-complexity=10 --max-line-lemngth=79 --statistics

            - name: Lint with pyLint
              run: |
                pylint src